version: '3.7'
services:
  mongodb:
    container_name: currency_dbs
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - currency_network
  currencyapp:
    container_name: currency_app
    restart: always
    build: .
    env_file: .env
    environment:
      - APIKEY=${APIKEY}
    ports:
      - 7654:7654
    links:
      - mongodb:mongodb
    depends_on:
      - mongodb
    networks:
      - currency_network
  client:
    container_name: currency_client
    restart: always
    build: ./client/
    ports:
      - 3000:3000
    links:
      - currencyapp:currencyapp
    depends_on:
      - currencyapp
    networks:
      - currency_network
networks:
  currency_network:
    external: false
    name: currency_network
volumes:
  mongodb_data_container: